version: '3.9'
services:
  # FastAPI
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - src/.env
    ports:
      - "8000:8000"
    # volumesはローカルにあるファイルをコンテナに転送させ、そのファイルの変更を反映する
    # volumes:  # for development only
    #   - .:/app
